name: Debug Token

on: [push]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Try Clone Homebrew Tap
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [ -z "$GH_TOKEN" ]; then
            echo "GH_TOKEN is empty!"
            exit 1
          fi
          git clone https://x-access-token:$GH_TOKEN@github.com/gabeosx/homebrew-skx.git test-repo
          cd test-repo
          ls -la
          git branch -a
