name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenenace
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Verify CI Quality Gate
        run: npm run lint && npm run build && npm test

      - name: Semantic Release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Get Version
        id: get_version
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Bump Homebrew formula
        uses: mislav/bump-homebrew-formula-action@v3
        if: github.ref == 'refs/heads/main'
        with:
          formula-name: skx
          homebrew-tap: gabeosx/homebrew-skx
          base-branch: main
          download-url: https://registry.npmjs.org/skx/-/skx-${{ steps.get_version.outputs.version }}.tgz
          commit-message: |
            Update skx to {{version}}

            Created by GitHub Actions
        env:
          COMMITTER_TOKEN: ${{ secrets.GH_TOKEN }}
